replicaCount: 1
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-orders
  tag: ab61290

containerPort: 8083

blueGreen:
  enabled: true
  autoPromotionEnabled: false

service:
  type: ClusterIP
  port: 8083

probePath: "/actuator/health/readiness"
readinessDelay: 60
livenessDelay: 80

env:
  - name: DB_USER_ORDERS
    value: "user_orders"
  - name: DB_PASSWORD_ORDERS
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_ORDERS