replicaCount: 3
image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-frontend
  tag: 5ee5502

containerPort: 3000

blueGreen:
  enabled: true
  autoPromotionEnabled: false 

service:
  type: LoadBalancer 
  port: 80           

probePath: "/" 
readinessDelay: 15
livenessDelay: 30

env:
  - name: NODE_ENV
    value: "production"
