replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8080
namespace: foodhub-dev

globalConfigMap: "global-configs"
globalSecret: "foodhub-secrets"

blueGreen:
  enabled: true
  autoPromotionEnabled: false

service:
  type: ClusterIP
  port: 80

probePath: "/actuator/health/readiness"
readinessDelay: 60
livenessDelay: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

env: []