replicaCount: 1

image:
  repository: 257394468168.dkr.ecr.ap-southeast-1.amazonaws.com/foodhub-products
  tag: f087607

containerPort: 8081

blueGreen:
  enabled: true
  autoPromotionEnabled: false

service:
  type: ClusterIP
  port: 8081

probePath: "/actuator/health/readiness"
readinessDelay: 90
livenessDelay: 120

env:
  - name: DB_USER_PRODUCTS
    value: "user_products"
  - name: DB_PASSWORD_PRODUCTS
    valueFrom:
      secretKeyRef:
        name: foodhub-secrets
        key: DB_PASSWORD_PRODUCTS